name: Release

on:
  release:
    types:
      - published
      - edited
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare release
        run: |
          cd ${{ github.workspace }}/custom_components/ha_keenetic
          zip -r ha_keenetic.zip ./
      - name: Upload zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/ha_keenetic/ha_keenetic.zip
          asset_name: ha_keenetic.zip
          tag: ${{ github.ref }}
          overwrite: true